(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'₹'+Number(v||0).toFixed(2);
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(d,n)=>{const x=new Date(d+'T00:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
let supa;
const D={a:[],c:[],l:[],e:[],p:[],t:[],s:[]};
function db(){if(!supa)supa=window.supabase.createClient(window.HFY_SUPABASE_URL,window.HFY_SUPABASE_PUBLISHABLE_KEY);return supa}
function fail(e){console.error(e);alert('Admin data/action error: '+(e?.message||e))}
window.show=(id,b)=>{document.querySelectorAll('.panel').forEach(x=>x.classList.remove('on'));const p=$(id);if(p)p.classList.add('on');document.querySelectorAll('.m').forEach(x=>x.classList.remove('on'));if(b)b.classList.add('on');render()};
window.openBox=(t,h)=>{$('mt').textContent=t;$('mb').innerHTML=h;$('modal').classList.add('on')};
window.closeM=()=>{$('modal').classList.remove('on')};
const customerName=id=>{const c=D.c.find(x=>String(x.id)===String(id));return c?.full_name||'-'};
const isPending=x=>['draft','submitted','under_review'].includes(String(x.status||'').toLowerCase());
async function loadData(){try{const q=[db().from('loan_applications').select('*').order('created_at',{ascending:false}),db().from('customers').select('*').order('created_at',{ascending:false}),db().from('loan_accounts').select('*').order('created_at',{ascending:false}),db().from('loan_emi_schedule').select('*').order('due_date'),db().from('loan_repayments').select('*').order('payment_date',{ascending:false}),db().from('financial_transactions').select('*').order('transaction_date',{ascending:false}),db().from('staff').select('*').order('created_at',{ascending:false})];const r=await Promise.all(q);for(const x of r)if(x.error)throw x.error;D.a=r[0].data||[];D.c=r[1].data||[];D.l=r[2].data||[];D.e=r[3].data||[];D.p=r[4].data||[];D.t=r[5].data||[];D.s=r[6].data||[];render()}catch(e){fail(e)}}
window.loadData=loadData;
function render(){
$('nA').textContent=D.a.length;$('nP').textContent=D.a.filter(isPending).length;$('nC').textContent=D.c.length;$('nL').textContent=D.l.length;const due=D.l.reduce((n,x)=>n+Number(x.remaining_amount||0),0);$('nD').textContent=money(due);$('reportDue').textContent=money(due);
$('appsRows').innerHTML=D.a.map((x,i)=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.mobile)}</td><td>${esc((x.applied_at||x.created_at||'').slice(0,10))}</td><td>${money(x.requested_amount)}</td><td>${esc(x.status)}</td><td><button class="btn gray" onclick="viewApp(${i})">View</button></td></tr>`).join('')||'<tr><td colspan="6">No applications.</td></tr>';
$('apRows').innerHTML=D.a.filter(isPending).map(x=>{const i=D.a.indexOf(x);return `<tr><td>${esc(x.full_name)}</td><td>${esc(x.mobile)}</td><td>${esc((x.applied_at||x.created_at||'').slice(0,10))}</td><td>${money(x.requested_amount)}</td><td class="pending">Pending for Approval</td><td><button class="btn blue" onclick="editApproval(${i})">Edit</button></td></tr>`}).join('')||'<tr><td colspan="6">No pending approval.</td></tr>';
const term=(($('search')||{}).value||'').toLowerCase();$('cuRows').innerHTML=D.c.filter(x=>(x.full_name+' '+x.mobile).toLowerCase().includes(term)).map((x,i)=>{const l=D.l.find(z=>String(z.customer_id)===String(x.id));return `<tr><td>${esc(x.full_name)}</td><td>${esc(x.mobile)}</td><td>${esc(l?.loan_id||'-')}</td><td>${money(l?.loan_amount||0)}</td><td>${esc(l?.start_date||'-')}</td><td><button class="btn blue" onclick="editCustomer(${i})">View / Edit</button><button class="btn red" onclick="deleteCustomer(${i})">Delete</button></td></tr>`}).join('')||'<tr><td colspan="6">No customers.</td></tr>';
$('reRows').innerHTML=D.e.map((x,i)=>{let st=x.status;if(st!=='paid'&&Number(x.remaining_amount||0)>0&&x.due_date<today())st='overdue';return `<tr><td>${esc(customerName(x.customer_id))}</td><td>${esc(D.c.find(c=>String(c.id)===String(x.customer_id))?.mobile||'')}</td><td>${esc(x.loan_id)}</td><td>${money(x.emi_amount)}</td><td>${esc(x.due_date)}</td><td>${money(x.penalty)}</td><td>${money(Number(x.emi_amount||0)+Number(x.penalty||0))}</td><td>${money(x.paid_amount)}</td><td>${money(x.remaining_amount)}</td><td>${esc(st)}</td><td><button class="btn blue" onclick="viewEmi(${i})">View</button></td></tr>`}).join('')||'<tr><td colspan="11">No EMI records.</td></tr>';
renderPayments();renderTransactions();renderOverdue();renderStaff();
}
function renderPayments(){$('payments').innerHTML='<h2>Payments</h2><button class="btn blue" onclick="addPayment()">+ Add Payment</button><div class="wrap"><table><tr><th>Customer</th><th>Loan ID</th><th>Amount</th><th>Date</th><th>Type</th><th>Status</th><th>Remarks</th></tr>'+(D.p.map(x=>`<tr><td>${esc(customerName(x.customer_id))}</td><td>${esc(x.loan_id)}</td><td>${money(x.amount)}</td><td>${esc(x.payment_date)}</td><td>${esc(x.payment_type)}</td><td>${esc(x.status)}</td><td>${esc(x.remarks||'')}</td></tr>`).join('')||'<tr><td colspan="7">No payments.</td></tr>')+'</table></div>'}
function renderTransactions(){$('transactions').innerHTML='<h2>Transactions</h2><div class="wrap"><table><tr><th>Transaction ID</th><th>Customer</th><th>Loan ID</th><th>Type</th><th>Amount</th><th>Status</th><th>Date</th></tr>'+(D.t.map(x=>`<tr><td>${esc(x.transaction_id)}</td><td>${esc(customerName(x.customer_id))}</td><td>${esc(x.loan_id)}</td><td>${esc(x.transaction_type)}</td><td>${money(x.amount)}</td><td>${esc(x.status)}</td><td>${esc((x.transaction_date||'').slice(0,10))}</td></tr>`).join('')||'<tr><td colspan="7">No transactions.</td></tr>')+'</table></div>'}
function renderOverdue(){$('ovRows').innerHTML=D.e.filter(x=>x.status!=='paid'&&Number(x.remaining_amount||0)>0&&x.due_date<today()).map(x=>`<tr><td>${esc(x.loan_id)}</td><td>${esc(customerName(x.customer_id))}</td><td>${money(x.emi_amount)}</td><td>${Math.max(0,Math.floor((Date.now()-new Date(x.due_date+'T00:00:00'))/86400000))}</td><td>${money(x.penalty)}</td><td>${money(x.remaining_amount)}</td><td><button class="btn green" onclick="paid('${x.id}')">Paid</button></td></tr>`).join('')||'<tr><td colspan="7">No overdue EMI.</td></tr>'}
function renderStaff(){$('staff').innerHTML='<h2>Staff/Admin</h2><button class="btn blue" onclick="addStaff()">+ Add Staff</button><div class="wrap"><table><tr><th>Employee ID</th><th>Name</th><th>Mobile</th><th>Email</th><th>Role</th><th>Status</th><th>Credentials</th></tr>'+(D.s.map((x,i)=>`<tr><td>${esc(x.employee_id)}</td><td>${esc(x.name)}</td><td>${esc(x.mobile||'')}</td><td>${esc(x.email||'')}</td><td>${esc(x.role)}</td><td>${esc(x.status)}</td><td><button class="btn gray" onclick="staffView(${i})">View</button></td></tr>`).join('')||'<tr><td colspan="7">No staff.</td></tr>')+'</table></div>'}
window.viewApp=i=>{const x=D.a[i];openBox('Application Details',`<p>Name: <b>${esc(x.full_name)}</b></p><p>Mobile: <b>${esc(x.mobile)}</b></p><p>Amount: <b>${money(x.requested_amount)}</b></p><p>Tenure: <b>${x.tenure_months} Month(s)</b></p><p>Status: <b>${esc(x.status)}</b></p><button class="btn blue" onclick="editApproval(${i})">Edit / Approval</button>`) };
window.editApproval=i=>{const x=D.a[i];openBox('Edit / Approval',`<div class="form"><label>Name<input id="an" value="${esc(x.full_name)}"></label><label>Mobile<input id="am" value="${esc(x.mobile)}"></label><label>Email<input id="ae" value="${esc(x.email||'')}"></label><label>DOB<input id="ad" type="date" value="${esc(x.date_of_birth||'')}"></label><label>Loan Amount<input id="aa" type="number" min="1000" max="20000" value="${x.requested_amount||0}"></label><label>Loan Tenure<select id="at"><option value="1">1 Month</option><option value="2">2 Months</option><option value="3">3 Months</option></select></label><label>Occupation<input id="ao" value="${esc(x.occupation||'')}"></label><label>Income<input id="ai" type="number" value="${x.monthly_income||''}"></label><label class="full">Address<input id="ax" value="${esc(x.address||'')}"></label><label>District<input id="adi" value="${esc(x.district||'')}"></label><label>State<input id="as" value="${esc(x.state||'')}"></label><label>Pincode<input id="ap" value="${esc(x.pincode||'')}"></label><label>PAN<input id="apan" value="${esc(x.pan_number||'')}"></label><label>Aadhaar<input id="aad" value="${esc(x.aadhaar_number||'')}"></label><label>KYC<select id="ak"><option>Pending</option><option>Under Review</option><option>Verified</option><option>Rejected</option></select></label><label>Bank Verification<input id="ab" value="${esc(x.bank_verification||'Pending')}"></label><label>Fraud Check<input id="af" value="${esc(x.fraud_check||'Pending')}"></label><label class="full">Remarks<input id="ar" value="${esc(x.admin_remarks||'')}"></label><div class="full"><button class="btn blue" onclick="saveApproval(${i})">Save Changes</button><button class="btn green" onclick="approve(${i})">Approve</button><button class="btn red" onclick="reject(${i})">Reject</button></div></div>`);$('at').value=String(x.tenure_months||1);$('ak').value=x.kyc_status||'Pending'};
function approval(){return {full_name:$('an').value.trim(),mobile:$('am').value.trim(),email:$('ae').value||null,date_of_birth:$('ad').value||null,requested_amount:Number($('aa').value||0),tenure_months:Number($('at').value||1),occupation:$('ao').value||null,monthly_income:Number($('ai').value||0)||null,address:$('ax').value||null,district:$('adi').value||null,state:$('as').value||null,pincode:$('ap').value||null,pan_number:$('apan').value||null,aadhaar_number:$('aad').value||null,kyc_status:$('ak').value,bank_verification:$('ab').value||'Pending',fraud_check:$('af').value||'Pending',admin_remarks:$('ar').value||null}}
function customerFields(p){return {full_name:p.full_name,mobile:p.mobile,email:p.email,date_of_birth:p.date_of_birth,occupation:p.occupation,monthly_income:p.monthly_income,address:p.address,district:p.district,state:p.state,pincode:p.pincode,pan_number:p.pan_number,aadhaar_number:p.aadhaar_number,kyc_status:p.kyc_status,updated_at:new Date().toISOString()}}
window.saveApproval=async i=>{try{const x=D.a[i],p=approval();if(!p.full_name||!p.mobile)return alert('Name and Mobile are required.');if(p.requested_amount<1000||p.requested_amount>20000)return alert('Loan amount must be ₹1,000 to ₹20,000.');let r=await db().from('loan_applications').update({...p,updated_at:new Date().toISOString()}).eq('id',x.id);if(r.error)throw r.error;if(x.customer_id){r=await db().from('customers').update(customerFields(p)).eq('id',x.customer_id);if(r.error)throw r.error}closeM();await loadData();alert('Update saved.')}catch(e){fail(e)}};
window.reject=async i=>{try{const r=await db().from('loan_applications').update({status:'rejected',updated_at:new Date().toISOString()}).eq('id',D.a[i].id);if(r.error)throw r.error;closeM();await loadData()}catch(e){fail(e)}};
window.approve=async i=>{try{const x=D.a[i],p=approval();if(p.requested_amount<1000||p.requested_amount>20000)return alert('Loan amount must be ₹1,000 to ₹20,000.');const total=p.requested_amount*(1+.20*p.tenure_months),monthly=total/p.tenure_months,daily=monthly/30,start=today(),end=addDays(start,p.tenure_months*30);let r=await db().from('loan_applications').update({...p,status:'approved',approved_amount:p.requested_amount,interest_rate:20,emi_amount:monthly,daily_emi:daily,total_interest:total-p.requested_amount,total_repayment:total}).eq('id',x.id);if(r.error)throw r.error;let cid=x.customer_id;if(cid){r=await db().from('customers').update({...customerFields(p),status:'active'}).eq('id',cid);if(r.error)throw r.error}else{r=await db().from('customers').insert({...customerFields(p),status:'active'}).select('id').single();if(r.error)throw r.error;cid=r.data.id}let q=await db().from('loan_accounts').select('*').eq('application_id',x.id).maybeSingle();if(q.error)throw q.error;let loan=q.data;if(!loan){r=await db().from('loan_accounts').insert({application_id:x.id,customer_id:cid,loan_amount:p.requested_amount,total_repayment:total,tenure_months:p.tenure_months,daily_emi:daily,total_paid:0,remaining_amount:total,penalty_amount:0,loan_status:'active',start_date:start,end_date:end}).select('*').single();if(r.error)throw r.error;loan=r.data}let count=await db().from('loan_emi_schedule').select('id',{count:'exact',head:true}).eq('loan_account_id',loan.id);if(count.error)throw count.error;if(!count.count){const rows=[];for(let n=1;n<=p.tenure_months;n++)rows.push({loan_account_id:loan.id,loan_id:loan.loan_id,customer_id:cid,emi_number:n,due_date:addDays(start,n*30),emi_amount:monthly,penalty:0,paid_amount:0,status:'upcoming'});r=await db().from('loan_emi_schedule').insert(rows);if(r.error)throw r.error}closeM();await loadData();alert('Approved. Loan ID '+loan.loan_id+' generated and EMI schedule created.')}catch(e){fail(e)}};
window.addCustomer=()=>openBox('Add Customer',`<div class="form"><label>Name<input id="cn"></label><label>Mobile<input id="cm"></label><label>Email<input id="ce"></label><label>DOB<input id="cd" type="date"></label><label>Loan Amount<input id="ca" type="number" min="1000" max="20000"></label><label>Tenure<select id="ct"><option value="1">1 Month</option><option value="2">2 Months</option><option value="3">3 Months</option></select></label><label>Occupation<input id="co"></label><label>Income<input id="ci" type="number"></label><label class="full">Address<input id="cx"></label><label>District<input id="cdist"></label><label>State<input id="cstate"></label><label>Pincode<input id="cpin"></label><label>PAN<input id="cpan"></label><label>Aadhaar<input id="caa"></label><div class="full"><button class="btn green" onclick="saveCustomer()">Save Customer</button></div></div>`);
window.saveCustomer=async()=>{try{const name=$('cn').value.trim(),mobile=$('cm').value.trim(),amount=Number($('ca').value||0),tenure=Number($('ct').value||1);if(!name||!mobile)return alert('Name and Mobile are required.');if(amount<1000||amount>20000)return alert('Loan amount must be ₹1,000 to ₹20,000.');const p={full_name:name,mobile,email:$('ce').value||null,date_of_birth:$('cd').value||null,occupation:$('co').value||null,monthly_income:Number($('ci').value||0)||null,address:$('cx').value||null,district:$('cdist').value||null,state:$('cstate').value||null,pincode:$('cpin').value||null,pan_number:$('cpan').value||null,aadhaar_number:$('caa').value||null,kyc_status:'Pending',status:'active'};let r=await db().from('customers').insert(p).select('id').single();if(r.error)throw r.error;r=await db().from('loan_applications').insert({...p,customer_id:r.data.id,requested_amount:amount,interest_rate:20,tenure_months:tenure,status:'submitted',bank_verification:'Pending',fraud_check:'Pending'});if(r.error)throw r.error;closeM();await loadData();alert('Customer saved and sent to Approval.')}catch(e){fail(e)}};
window.editCustomer=i=>{const x=D.c[i];openBox('Customer View / Edit',`<div class="form"><label>Name<input id="en" value="${esc(x.full_name)}"></label><label>Mobile<input id="em" value="${esc(x.mobile)}"></label><label>Email<input id="ee" value="${esc(x.email||'')}"></label><label>DOB<input id="ed" type="date" value="${esc(x.date_of_birth||'')}"></label><label>Occupation<input id="eo" value="${esc(x.occupation||'')}"></label><label>Income<input id="ei" type="number" value="${x.monthly_income||''}"></label><label class="full">Address<input id="ex" value="${esc(x.address||'')}"></label><label>District<input id="edi" value="${esc(x.district||'')}"></label><label>State<input id="es" value="${esc(x.state||'')}"></label><label>Pincode<input id="ep" value="${esc(x.pincode||'')}"></label><label>PAN<input id="epan" value="${esc(x.pan_number||'')}"></label><label>Aadhaar<input id="eaa" value="${esc(x.aadhaar_number||'')}"></label><div class="full"><button class="btn blue" onclick="saveCustomerEdit(${i})">Save Changes</button></div></div>`)};
window.saveCustomerEdit=async i=>{try{const x=D.c[i],p={full_name:$('en').value.trim(),mobile:$('em').value.trim(),email:$('ee').value||null,date_of_birth:$('ed').value||null,occupation:$('eo').value||null,monthly_income:Number($('ei').value||0)||null,address:$('ex').value||null,district:$('edi').value||null,state:$('es').value||null,pincode:$('epin').value||null,pan_number:$('epan').value||null,aadhaar_number:$('eaa').value||null,updated_at:new Date().toISOString()};if(!p.full_name||!p.mobile)return alert('Name and Mobile are required.');let r=await db().from('customers').update(p).eq('id',x.id);if(r.error)throw r.error;closeM();await loadData()}catch(e){fail(e)}};
window.deleteCustomer=async i=>{if(!confirm('Delete customer and pending application?'))return;try{const x=D.c[i];let r=await db().from('loan_applications').delete().eq('customer_id',x.id).in('status',['draft','submitted','under_review']);if(r.error)throw r.error;r=await db().from('customers').delete().eq('id',x.id);if(r.error)throw r.error;await loadData()}catch(e){fail(e)}};
window.viewEmi=i=>{const x=D.e[i];openBox('EMI Details',`<p>Customer: <b>${esc(customerName(x.customer_id))}</b></p><p>Loan ID: <b>${esc(x.loan_id)}</b></p><p>EMI No: <b>${x.emi_number}</b></p><p>Due: <b>${esc(x.due_date)}</b></p><p>Amount: <b>${money(x.emi_amount)}</b></p><p>Penalty: <b>${money(x.penalty)}</b></p><p>Paid: <b>${money(x.paid_amount)}</b></p><p>Remaining: <b>${money(x.remaining_amount)}</b></p><button class="btn green" onclick="paid('${x.id}')">Paid</button>`)};
window.paid=async id=>{try{const x=D.e.find(e=>String(e.id)===String(id));const r=await db().from('loan_emi_schedule').update({paid_amount:Number(x.emi_amount||0)+Number(x.penalty||0),status:'paid',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;closeM();await loadData()}catch(e){fail(e)}};
window.addEmi=()=>{if(!D.l.length)return alert('No approved loan available.');const l=D.l[0];openBox('Add EMI',`<label>Loan ID<input value="${l.loan_id}" readonly></label><label>EMI No<input id="eno" type="number"></label><label>Due Date<input id="edate" type="date" value="${today()}"></label><label>Amount<input id="eamt" type="number" value="${Number(l.daily_emi||0)*30}"></label><button class="btn green" onclick="saveNewEmi('${l.id}','${l.loan_id}','${l.customer_id}')">Add EMI</button>`) };
window.saveNewEmi=async(a,l,c)=>{try{const r=await db().from('loan_emi_schedule').insert({loan_account_id:a,loan_id:Number(l),customer_id:Number(c),emi_number:Number($('eno').value),due_date:$('edate').value,emi_amount:Number($('eamt').value),penalty:0,paid_amount:0,status:'upcoming'});if(r.error)throw r.error;closeM();await loadData()}catch(e){fail(e)}};
window.addPayment=()=>{if(!D.l.length)return alert('No approved loan available.');const l=D.l[0];openBox('Add Payment',`<label>Loan ID<input value="${l.loan_id}" readonly></label><label>Amount<input id="pamt" type="number"></label><label>Date<input id="pdate" type="date" value="${today()}"></label><label>Type<input id="ptype" value="emi"></label><label>Remarks<input id="prem"></label><button class="btn green" onclick="savePayment('${l.id}','${l.loan_id}','${l.customer_id}')">Save Payment</button>`) };
window.savePayment=async(a,l,c)=>{try{const amount=Number($('pamt').value||0);if(amount<=0)return alert('Enter payment amount.');const tx='TXN-'+Date.now();let r=await db().from('loan_repayments').insert({loan_account_id:a,loan_id:Number(l),customer_id:Number(c),amount,payment_date:$('pdate').value,payment_type:$('ptype').value,status:'received',remarks:$('prem').value||null,transaction_id:tx});if(r.error)throw r.error;r=await db().from('financial_transactions').insert({transaction_id:tx,customer_id:Number(c),loan_account_id:a,loan_id:Number(l),amount,transaction_type:'EMI_PAYMENT',payment_method:'other',status:'successful',notes:$('prem').value||null});if(r.error)throw r.error;closeM();await loadData()}catch(e){fail(e)}};
window.addStaff=()=>openBox('Add Staff',`<label>Name<input id="sn"></label><label>Mobile<input id="sm"></label><label>Email<input id="se"></label><label>Role<select id="sr"><option>verifier</option><option>loan_officer</option><option>collection_officer</option><option>manager</option><option>custom_staff</option></select></label><button class="btn green" onclick="saveStaff()">Generate ID & Password</button>`);
window.saveStaff=async()=>{try{const name=$('sn').value.trim();if(!name)return alert('Name is required.');const employee='HFY-'+Date.now().toString().slice(-6),login='HFY'+Date.now().toString().slice(-6),password=Math.random().toString(36).slice(2,10).toUpperCase();let r=await db().from('staff').insert({employee_id:employee,name,mobile:$('sm').value||null,email:$('se').value||null,role:$('sr').value,status:'active'}).select('id').single();if(r.error)throw r.error;r=await db().from('staff_credentials').insert({staff_id:r.data.id,login_id:login,login_password:password});if(r.error)throw r.error;r=await db().from('staff_permissions').insert({staff_id:r.data.id});if(r.error)throw r.error;await loadData();openBox('Staff Login Created',`<p>Employee ID: <b>${esc(employee)}</b></p><p>Login ID: <b>${esc(login)}</b></p><p>Password: <b>${esc(password)}</b></p>`)}catch(e){fail(e)}};
window.staffView=async i=>{try{const s=D.s[i],r=await db().from('staff_credentials').select('login_id,login_password').eq('staff_id',s.id).maybeSingle();if(r.error)throw r.error;openBox('Staff Credentials',`<p>Employee ID: <b>${esc(s.employee_id)}</b></p><p>Login ID: <b>${esc(r.data?.login_id||'-')}</b></p><p>Password: <b>${esc(r.data?.login_password||'-')}</b></p>`)}catch(e){fail(e)}};
loadData();
})();