/* HELP FOR YOU — Admin Master Runtime
   Keeps the existing admin.html UI/options and makes every section functional.
   Uses the existing Supabase configuration and database tables.
*/
(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
var money=function(v){return Number(v||0).toFixed(2);};
var today=function(){return new Date().toISOString().slice(0,10);};
var client=null;
var db={applications:[],customers:[],loans:[],emis:[],payments:[],transactions:[],staff:[]};
window.HFY_ADMIN_DB=db;

function getClient(){
  if(client)return client;
  if(window.supabase&&window.HFY_SUPABASE_URL&&window.HFY_SUPABASE_PUBLISHABLE_KEY){
    client=window.supabase.createClient(window.HFY_SUPABASE_URL,window.HFY_SUPABASE_PUBLISHABLE_KEY);
    window.HFY_ADMIN_SB=client;
  }
  return client;
}
function err(e){console.error(e);return e&&e.message?e.message:String(e);}
function show(id,b){document.querySelectorAll('.panel').forEach(function(x){x.classList.remove('on');});var p=$(id);if(p)p.classList.add('on');document.querySelectorAll('.m').forEach(function(x){x.classList.remove('on');});if(b)b.classList.add('on');}
window.show=show;
function openBox(t,h){if($('mt'))$('mt').textContent=t;if($('mb'))$('mb').innerHTML=h;if($('modal'))$('modal').classList.add('on');}
window.openBox=openBox;
function closeM(){if($('modal'))$('modal').classList.remove('on');}
window.closeM=closeM;

async function loadData(){
 var sb=getClient();
 if(!sb){alert('Supabase client is not available.');return;}
 try{
  var r=await Promise.all([
   sb.from('loan_applications').select('*').order('created_at',{ascending:false}),
   sb.from('customers').select('*').order('created_at',{ascending:false}),
   sb.from('loan_accounts').select('*').order('created_at',{ascending:false}),
   sb.from('loan_emi_schedule').select('*').order('due_date',{ascending:true}),
   sb.from('loan_repayments').select('*').order('payment_date',{ascending:false}),
   sb.from('financial_transactions').select('*').order('transaction_date',{ascending:false}),
   sb.from('hfy_staff').select('*').order('created_at',{ascending:false})
  ]);
  for(var i=0;i<r.length;i++)if(r[i].error)throw r[i].error;
  var customers=r[1].data||[], cm=new Map(customers.map(function(c){return [String(c.id),c];}));
  db.applications=(r[0].data||[]).map(function(x){return Object.assign({},x,{name:x.name||x.full_name||'',amount:Number(x.requested_amount!=null?x.requested_amount:(x.loan_amount||0)),date:x.created_at?x.created_at.slice(0,10):''});});
  db.emis=(r[3].data||[]).map(function(e){var due=e.due_date;var d=due?Math.max(0,Math.floor((new Date().setHours(0,0,0,0)-new Date(due+'T00:00:00'))/86400000)):0;var st=String(e.status||'pending').toLowerCase();if(st!=='paid'&&due&&due<today())st='overdue';return {raw:e,id:e.id,loanId:String(e.loan_id||''),customer:(cm.get(String(e.customer_id))||{}).full_name||'',no:e.emi_number,due:due,amount:Number(e.emi_amount||0),days:d,penalty:Number(e.penalty||0),totalDue:Number(e.total_due!=null?e.total_due:(Number(e.emi_amount||0)+Number(e.penalty||0))),paid:Number(e.paid_amount||0),remaining:Number(e.remaining_amount!=null?e.remaining_amount:Math.max(0,Number(e.emi_amount||0)+Number(e.penalty||0)-Number(e.paid_amount||0))),status:st};});
  db.loans=(r[2].data||[]).map(function(l){var c=cm.get(String(l.customer_id))||{};var es=db.emis.filter(function(e){return String(e.loanId)===String(l.loan_id);});return {raw:l,id:l.id,loanId:String(l.loan_id),customerId:l.customer_id,name:c.full_name||'',mobile:c.mobile||'',email:c.email||'',amount:Number(l.loan_amount||0),months:Number(l.tenure_months||0),dailyEmi:Number(l.daily_emi||0),emi:Number(l.daily_emi||0)*30,total:Number(l.total_repayment||0),paid:Number(l.total_paid||0),remaining:Number(l.remaining_amount!=null?l.remaining_amount:0),penalty:Number(l.penalty_amount||0),status:l.loan_status||'active',sanction:l.start_date||'',end:l.end_date||'',accountId:l.id,pan:c.pan_number||'',aadhaar:c.aadhaar_number||'',address:c.address||'',state:c.state||'',district:c.district||'',pincode:c.pincode||'',overdue:es.reduce(function(s,e){return s+Number(e.penalty||0);},0),due:es.length?es.reduce(function(s,e){return s+Math.max(0,e.remaining);},0):Number(l.remaining_amount||0)};});
  db.customers=(customers||[]).map(function(c){var loans=db.loans.filter(function(l){return String(l.customerId)===String(c.id);});var l=loans[0];return {raw:c,id:c.id,name:c.full_name||'',mobile:c.mobile||'',email:c.email||'',dob:c.date_of_birth||'',address:c.address||'',occupation:c.occupation||'',income:c.monthly_income||'',kyc:c.kyc_status||'',status:c.status||c.account_status||'',state:c.state||'',district:c.district||'',pincode:c.pincode||'',pan:c.pan_number||'',aadhaar:c.aadhaar_number||c.adhar_number||'',loanId:l?l.loanId:'',amount:l?l.amount:0,sanction:l?l.sanction:'',loan:l||null};});
  db.payments=r[4].data||[];db.transactions=r[5].data||[];db.staff=r[6].data||[];
  window.db=db;window.render=render;render();
 }catch(e){console.error(e);alert('Admin data load error: '+err(e));}
}
window.loadData=loadData;

function render(){
 var pending=db.applications.filter(function(x){return !['approved','rejected','disbursed'].includes(String(x.status||'').toLowerCase());});
 if($('nA'))$('nA').textContent=db.applications.length;if($('nP'))$('nP').textContent=pending.length;if($('nC'))$('nC').textContent=db.customers.length;if($('nL'))$('nL').textContent=db.loans.length;
 var due=db.loans.reduce(function(s,x){return s+Number(x.due||0);},0);if($('nD'))$('nD').textContent='₹'+money(due);if($('reportDue'))$('reportDue').textContent='₹'+money(due);
 if($('appsRows'))$('appsRows').innerHTML=db.applications.map(function(x,i){return '<tr><td>'+esc(x.name)+'</td><td>'+esc(x.mobile)+'</td><td>'+esc(x.date)+'</td><td>₹'+money(x.amount)+'</td><td>'+esc(x.status||'pending')+'</td><td><button class="btn gray" onclick="viewApp('+i+')">View</button></td></tr>';}).join('')||'<tr><td colspan="6">No applications.</td></tr>';
 if($('apRows'))$('apRows').innerHTML=db.applications.map(function(x,i){if(['approved','rejected','disbursed'].includes(String(x.status||'').toLowerCase()))return '';return '<tr><td>'+esc(x.name)+'</td><td>'+esc(x.mobile)+'</td><td>'+esc(x.date)+'</td><td>₹'+money(x.amount)+'</td><td class="pending">Pending for Approval</td><td><button class="btn blue" onclick="editApproval('+i+')">Edit</button></td></tr>';}).join('')||'<tr><td colspan="6">No pending approval.</td></tr>';
 var q=(($('search')||{}).value||'').toLowerCase();if($('cuRows'))$('cuRows').innerHTML=db.customers.filter(function(x){return JSON.stringify(x).toLowerCase().includes(q);}).map(function(x,i){return '<tr><td>'+esc(x.name)+'</td><td>'+esc(x.mobile)+'</td><td>'+esc(x.loanId)+'</td><td>₹'+money(x.amount)+'</td><td>'+esc(x.sanction)+'</td><td><button class="btn blue" onclick="editCustomer('+i+')">View / Edit</button></td></tr>';}).join('')||'<tr><td colspan="6">No customers.</td></tr>';
 if($('reRows'))$('reRows').innerHTML=db.loans.map(function(x,i){return '<tr><td>'+esc(x.name)+'</td><td>'+esc(x.mobile)+'</td><td>'+esc(x.loanId)+'</td><td>₹'+money(x.amount)+'</td><td>20% / month</td><td>'+esc(x.sanction)+'</td><td>₹'+money(x.emi)+'</td><td>₹'+money(x.overdue)+'</td><td>₹'+money(x.due)+'</td><td><button class="btn blue" onclick="viewRepay('+i+')">View</button></td></tr>';}).join('')||'<tr><td colspan="10">No loans.</td></tr>';
 if($('ovRows'))$('ovRows').innerHTML=db.emis.filter(function(e){return e.status==='overdue'&&e.remaining>0;}).map(function(e){return '<tr><td>'+esc(e.loanId)+'</td><td>'+esc(e.customer)+'</td><td>₹'+money(e.amount)+'</td><td>'+e.days+'</td><td>₹'+money(e.penalty)+'</td><td>₹'+money(e.remaining)+'</td><td><button class="btn green" onclick="pay(\''+esc(e.id)+'\')">Paid</button></td></tr>';}).join('')||'<tr><td colspan="7">No overdue EMI.</td></tr>';
 renderPayments();renderTransactions();renderStaff();
}
window.render=render;
function refresh(){return loadData();}

window.viewApp=function(i){var x=db.applications[i];if(!x)return;openBox('Application Details','<div class="form">'+field('Name','v1',x.name)+field('Mobile','v2',x.mobile)+field('Apply Date','v3',x.date)+field('Loan Amount','v4',x.amount)+field('Email','v5',x.email)+field('DOB','v6',x.date_of_birth)+field('Gender','v7',x.gender)+field('Occupation','v8',x.occupation)+field('Monthly Income','v9',x.monthly_income)+field('Loan Purpose','v10',x.loan_purpose)+field('Address','v11',x.address)+field('State','v12',x.state)+field('District','v13',x.city||'')+field('Pincode','v14',x.pincode)+field('PAN','v15',x.pan_number)+field('Bank','v16',x.bank_name)+field('IFSC','v17',x.ifsc_code)+field('KYC','v18',x.kyc_status)+field('Bank Verification','v19',x.bank_verification)+field('Fraud Check','v20',x.fraud_check)+field('Status','v21',x.status)+'</div><div class="actions"><button class="btn blue" onclick="editApproval('+i+')">Edit / Approval</button></div>');};
function field(label,id,val){return '<label>'+esc(label)+'<input id="'+id+'" value="'+esc(val)+'" readonly></label>';}

window.editApproval=function(i){var x=db.applications[i];if(!x)return;openBox('Edit / Approval','<div class="form">'+editField('Name','fxn',x.name)+editField('Mobile','fxm',x.mobile)+editField('Apply Date','fxdate',x.date,'date')+editField('Loan Amount','fxa',x.amount,'number')+editField('Email','fxemail',x.email)+editField('DOB','fxdob',x.date_of_birth,'date')+editField('Gender','fxgender',x.gender)+editField('Occupation','fxocc',x.occupation)+editField('Monthly Income','fxincome',x.monthly_income,'number')+editField('Loan Purpose','fxpurpose',x.loan_purpose)+editField('Address','fxaddr',x.address)+editField('State','fxstate',x.state)+editField('District','fxcity',x.city)+editField('Pincode','fxpin',x.pincode)+editField('PAN','fxpan',x.pan_number)+editField('Aadhaar','fxaad',x.aadhaar_number)+editField('Bank Name','fxbank',x.bank_name)+editField('IFSC','fxifsc',x.ifsc_code)+editField('Account Number','fxacct',x.account_number||x.bank_account)+editField('KYC Status','fxkyc',x.kyc_status)+editField('Bank Verification','fxbv',x.bank_verification)+editField('Fraud Check','fxfraud',x.fraud_check)+editField('Remarks','fxremarks',x.admin_remarks,'text',true)+'<label>Status<select id="fxstatus"><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><div class="full"><button class="btn blue" onclick="saveApproval('+i+')">Save Changes</button><button class="btn green" onclick="approve('+i+')">Approve & Generate Loan</button><button class="btn red" onclick="reject('+i+')">Reject</button></div></div>');$('fxstatus').value=x.status||'pending';};
function editField(label,id,val,type,full){return '<label'+(full?' class="full"':'')+'>'+esc(label)+'<input id="'+id+'" type="'+(type||'text')+'" value="'+esc(val==null?'':val)+'"></label>';}
function appPayload(){return {name:$('fxn').value,full_name:$('fxn').value,mobile:$('fxm').value,created_at:undefined,requested_amount:Number($('fxa').value||0),loan_amount:Number($('fxa').value||0),email:$('fxemail').value||null,date_of_birth:$('fxdob').value||null,gender:$('fxgender').value||null,occupation:$('fxocc').value||null,monthly_income:Number($('fxincome').value||0)||null,loan_purpose:$('fxpurpose').value||null,address:$('fxaddr').value||null,state:$('fxstate').value||null,city:$('fxcity').value||null,pincode:$('fxpin').value||null,pan_number:$('fxpan').value||null,aadhaar_number:$('fxaad').value||null,bank_name:$('fxbank').value||null,ifsc_code:$('fxifsc').value||null,account_number:$('fxacct').value||null,bank_account:$('fxacct').value||null,kyc_status:$('fxkyc').value||null,bank_verification:$('fxbv').value||null,fraud_check:$('fxfraud').value||null,admin_remarks:$('fxremarks').value||null,status:$('fxstatus').value,updated_at:new Date().toISOString()};}
window.saveApproval=async function(i){var x=db.applications[i],sb=getClient();if(!x)return;var p=appPayload();delete p.created_at;var r=await sb.from('loan_applications').update(p).eq('id',x.id);if(r.error)return alert(err(r.error));closeM();await loadData();alert('Application updated successfully.');};
window.approve=async function(i){var x=db.applications[i],sb=getClient();if(!x)return;var a=Number($('fxa').value||0),m=a<=5000?1:a<=10000?2:a<=20000?3:0;if(!m)return alert('Loan amount must be ₹1,000 to ₹20,000.');var t=a+a*.2*m,daily=t/(m*30),p=appPayload();p.status='approved';p.approved_amount=a;p.interest_rate=20;p.tenure=m;p.tenure_months=m;p.emi_amount=t/m;p.daily_emi=daily;p.total_interest=a*.2*m;p.total_repayment=t;delete p.created_at;var r=await sb.from('loan_applications').update(p).eq('id',x.id);if(r.error)return alert(err(r.error));var cid=x.customer_id;if(cid){r=await sb.from('customers').update({full_name:p.full_name,mobile:p.mobile,email:p.email,date_of_birth:p.date_of_birth,address:p.address,occupation:p.occupation,monthly_income:p.monthly_income,state:p.state,district:p.city,pincode:p.pincode,pan_number:p.pan_number,aadhaar_number:p.aadhaar_number,kyc_status:p.kyc_status,updated_at:new Date().toISOString()}).eq('id',cid);}else{r=await sb.from('customers').insert({full_name:p.full_name,mobile:p.mobile,email:p.email,date_of_birth:p.date_of_birth,address:p.address,occupation:p.occupation,monthly_income:p.monthly_income,state:p.state,district:p.city,pincode:p.pincode,pan_number:p.pan_number,aadhaar_number:p.aadhaar_number,kyc_status:p.kyc_status,status:'active'}).select('id').single();cid=r.data&&r.data.id;}if(r.error)return alert(err(r.error));var q=await sb.from('loan_accounts').select('loan_id').order('loan_id',{ascending:false}).limit(1);if(q.error)return alert(err(q.error));var lid=(q.data&&q.data[0]?Number(q.data[0].loan_id):0)+1;var start=$('fxdate').value||today(),end=new Date(start+'T00:00:00');end.setDate(end.getDate()+m*30);r=await sb.from('loan_accounts').insert({loan_id:lid,customer_id:cid,loan_amount:a,total_repayment:t,tenure_months:m,daily_emi:daily,total_paid:0,remaining_amount:t,penalty_amount:0,loan_status:'active',start_date:start,end_date:end.toISOString().slice(0,10),application_id:x.id}).select('id').single();if(r.error)return alert(err(r.error));var rows=[];for(var n=1;n<=m*30;n++){var d=new Date(start+'T00:00:00');d.setDate(d.getDate()+n);rows.push({loan_account_id:r.data.id,loan_id:lid,customer_id:cid,emi_number:n,due_date:d.toISOString().slice(0,10),emi_amount:daily,penalty:0,total_due:daily,paid_amount:0,remaining_amount:daily,status:'pending'});}r=await sb.from('loan_emi_schedule').insert(rows);if(r.error)return alert(err(r.error));closeM();await loadData();alert('Approved. Loan ID: '+lid+' and '+rows.length+' EMI entries created.');};
window.reject=async function(i){var sb=getClient(),x=db.applications[i];var r=await sb.from('loan_applications').update({status:'rejected',updated_at:new Date().toISOString()}).eq('id',x.id);if(r.error)return alert(err(r.error));closeM();await loadData();alert('Application rejected.');};

window.addCustomer=function(){openBox('Add Customer','<div class="form">'+editField('Full Name','acn','')+editField('Mobile','acm','')+editField('Email','ace','')+editField('DOB','acdob','','date')+editField('PAN','acpan','')+editField('Aadhaar','acaad','')+editField('State','acstate','')+editField('District','acdist','')+editField('Pincode','acpin','')+editField('Occupation','acocc','')+editField('Monthly Income','acin','','number')+editField('Loan Amount','acloan','','number')+editField('Address','acaddr','', 'text',true)+'<div class="full"><button class="btn green" onclick="saveCustomer()">Save Customer</button></div></div>');};
window.saveCustomer=async function(){var sb=getClient(),n=$('acn').value,m=$('acm').value,a=Number($('acloan').value||0);if(!n||!m)return alert('Name and Mobile are required.');var r=await sb.from('customers').insert({full_name:n,mobile:m,email:$('ace').value||null,date_of_birth:$('acdob').value||null,pan_number:$('acpan').value||null,aadhaar_number:$('acaad').value||null,state:$('acstate').value||null,district:$('acdist').value||null,pincode:$('acpin').value||null,occupation:$('acocc').value||null,monthly_income:Number($('acin').value||0)||null,address:$('acaddr').value||null,status:'active'}).select('id').single();if(r.error)return alert(err(r.error));if(a>0){var app={customer_id:r.data.id,full_name:n,name:n,mobile:m,email:$('ace').value||null,date_of_birth:$('acdob').value||null,pan_number:$('acpan').value||null,aadhaar_number:$('acaad').value||null,state:$('acstate').value||null,city:$('acdist').value||null,pincode:$('acpin').value||null,occupation:$('acocc').value||null,monthly_income:Number($('acin').value||0)||null,address:$('acaddr').value||null,requested_amount:a,loan_amount:a,status:'pending'};r=await sb.from('loan_applications').insert(app);if(r.error)return alert('Customer saved but approval application failed: '+err(r.error));}closeM();await loadData();alert(a>0?'Customer saved and sent to Approval.':'Customer saved successfully.');};
window.editCustomer=function(i){var x=db.customers[i];if(!x)return;openBox('Customer Details / Edit','<div class="form">'+editField('Full Name','ecn',x.name)+editField('Mobile','ecm',x.mobile)+editField('Email','ece',x.email)+editField('DOB','ecdob',x.dob,'date')+editField('PAN','ecpan',x.pan)+editField('Aadhaar','ecaad',x.aadhaar)+editField('State','ecstate',x.state)+editField('District','ecdist',x.district)+editField('Pincode','ecpin',x.pincode)+editField('Occupation','ecocc',x.occupation)+editField('Monthly Income','ecinc',x.income,'number')+editField('Status','ecstatus',x.status)+editField('Address','ecaddr',x.address,'text',true)+'<div class="full"><button class="btn green" onclick="saveCustomerEdit('+i+')">Save Changes</button></div></div>');};
window.saveCustomerEdit=async function(i){var x=db.customers[i],sb=getClient();var r=await sb.from('customers').update({full_name:$('ecn').value,mobile:$('ecm').value,email:$('ece').value||null,date_of_birth:$('ecdob').value||null,pan_number:$('ecpan').value||null,aadhaar_number:$('ecaad').value||null,state:$('ecstate').value||null,district:$('ecdist').value||null,pincode:$('ecpin').value||null,occupation:$('ecocc').value||null,monthly_income:Number($('ecinc').value||0)||null,status:$('ecstatus').value||null,address:$('ecaddr').value||null,updated_at:new Date().toISOString()}).eq('id',x.id);if(r.error)return alert(err(r.error));closeM();await loadData();alert('Customer updated successfully.');};

window.viewRepay=function(i){var x=db.loans[i],es=db.emis.filter(function(e){return String(e.loanId)===String(x.loanId);});var totalPaid=es.reduce(function(s,e){return s+e.paid;},0);openBox('Full EMI List — Loan '+esc(x.loanId),'<p><b>'+esc(x.name)+'</b> | Loan ₹'+money(x.amount)+' | Total ₹'+money(x.total)+' | Paid ₹'+money(totalPaid)+' | Remaining ₹'+money(Math.max(0,x.total-totalPaid))+'</p><div class="wrap"><table><tr><th>EMI</th><th>Due Date</th><th>Amount</th><th>Penalty</th><th>Total Due</th><th>Paid</th><th>Remaining</th><th>Status</th><th>Action</th></tr>'+es.map(function(e){var st=e.status==='paid'?'paid':(e.status==='overdue'?'over':'pending');return '<tr><td>'+e.no+'</td><td>'+esc(e.due)+'</td><td>₹'+money(e.amount)+'</td><td>₹'+money(e.penalty)+'</td><td>₹'+money(e.totalDue)+'</td><td>₹'+money(e.paid)+'</td><td>₹'+money(e.remaining)+'</td><td class="'+st+'">'+esc(e.status)+'</td><td>'+(e.status==='paid'?'<span class="paid">Paid</span>':'<button class="btn green" onclick="pay(\''+esc(e.id)+'\')">Paid</button>')+' <button class="btn gray" onclick="editEmi(\''+esc(e.id)+'\')">Edit</button></td></tr>';}).join('')+'</table></div>');};
window.editEmi=function(id){var e=db.emis.find(function(x){return String(x.id)===String(id);});if(!e)return;openBox('Edit EMI','<div class="form">'+editField('EMI Number','emino',e.no,'number')+editField('Due Date','edue',e.due,'date')+editField('Amount','eamt',e.amount,'number')+editField('Penalty','epen',e.penalty,'number')+editField('Paid Amount','epaid',e.paid,'number')+'<label>Status<select id="estatus"><option value="pending">Pending</option><option value="overdue">Overdue</option><option value="paid">Paid</option></select></label><div class="full"><button class="btn blue" onclick="updateEmi(\''+esc(id)+'\')">Save Changes</button></div></div>');$('estatus').value=e.status;};
window.updateEmi=async function(id){var sb=getClient(),e=db.emis.find(function(x){return String(x.id)===String(id);}),a=Number($('eamt').value||0),pen=Number($('epen').value||0),paid=Number($('epaid').value||0),st=$('estatus').value;if(a<=0)return alert('Amount must be greater than 0.');var total=a+pen,remaining=st==='paid'?0:Math.max(0,total-paid);var r=await sb.from('loan_emi_schedule').update({emi_number:Number($('emino').value||e.no),due_date:$('edue').value,emi_amount:a,penalty:pen,total_due:total,paid_amount:st==='paid'?total:paid,remaining_amount:remaining,status:st,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return alert(err(r.error));closeM();await loadData();alert('EMI updated successfully.');};
window.pay=async function(id){var sb=getClient(),e=db.emis.find(function(x){return String(x.id)===String(id);});if(!e)return;if(e.status==='paid')return alert('This EMI is already paid.');var amount=Math.max(0,e.remaining);var r=await sb.from('loan_emi_schedule').update({paid_amount:e.totalDue,remaining_amount:0,status:'paid',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return alert(err(r.error));var loan=db.loans.find(function(l){return String(l.loanId)===String(e.loanId);});if(loan){var newPaid=loan.paid+amount,newRem=Math.max(0,loan.remaining-amount);r=await sb.from('loan_accounts').update({total_paid:newPaid,remaining_amount:newRem,loan_status:newRem<=0?'closed':loan.status}).eq('id',loan.accountId);if(r.error)return alert(err(r.error));var tr={transaction_id:'EMI-'+Date.now(),customer_id:loan.customerId,loan_account_id:loan.accountId,loan_id:Number(loan.loanId),emi_id:e.id,amount:amount,transaction_type:'EMI_PAYMENT',payment_method:'other',transaction_date:new Date().toISOString(),status:'successful',notes:'EMI payment from Admin'};var tx=await sb.from('financial_transactions').insert(tr);if(tx.error)console.warn(tx.error);}await loadData();closeM();alert('EMI marked as Paid successfully.');};
window.addEmi=function(){openBox('Add EMI','<div class="form">'+editField('Loan ID','ali','')+editField('Due Date','ald','', 'date')+editField('Amount','ala','','number')+editField('Penalty','alp','0','number')+'<div class="full"><button class="btn blue" onclick="saveEmi()">Save EMI</button></div></div>');};
window.saveEmi=async function(){var sb=getClient(),lid=$('ali').value,a=Number($('ala').value||0),date=$('ald').value,pen=Number($('alp').value||0);if(!lid||!a||!date)return alert('Loan ID, Due Date and Amount are required.');var r=await sb.from('loan_accounts').select('id,loan_id,customer_id').eq('loan_id',lid).maybeSingle();if(r.error||!r.data)return alert(r.error?err(r.error):'Loan ID not found.');var count=db.emis.filter(function(e){return String(e.loanId)===String(lid);}).length;var total=a+pen;r=await sb.from('loan_emi_schedule').insert({loan_account_id:r.data.id,loan_id:r.data.loan_id,customer_id:r.data.customer_id,emi_number:count+1,due_date:date,emi_amount:a,penalty:pen,total_due:total,paid_amount:0,remaining_amount:total,status:date<today()?'overdue':'pending'});if(r.error)return alert(err(r.error));closeM();await loadData();alert('EMI added successfully.');};

function renderPayments(){var p=$('payments');if(!p)return;var html='<h2>Payments</h2><div class="actions"><button class="btn blue" onclick="addPayment()">+ Add Payment</button></div><div class="wrap"><table><tr><th>Payment ID</th><th>Loan ID</th><th>Customer</th><th>Amount</th><th>Date</th><th>Type</th><th>Status</th><th>Remarks</th></tr>';db.payments.forEach(function(x){var l=db.loans.find(function(z){return String(z.loanId)===String(x.loan_id);});html+='<tr><td>'+esc(x.id)+'</td><td>'+esc(x.loan_id)+'</td><td>'+esc(l?l.name:'')+'</td><td>₹'+money(x.payment_amount!=null?x.payment_amount:x.amount)+'</td><td>'+esc(x.payment_date||'')+'</td><td>'+esc(x.payment_type||'')+'</td><td>'+esc(x.status||'')+'</td><td>'+esc(x.remarks||'')+'</td></tr>';});html+='</table></div>';p.innerHTML=html;}
window.addPayment=function(){openBox('Add Payment','<div class="form">'+editField('Loan ID','payloan','')+editField('Amount','payamt','','number')+editField('Payment Date','paydate',today(),'date')+editField('Payment Type','paytype','EMI')+editField('Remarks','payremark','','text',true)+'<div class="full"><button class="btn green" onclick="savePayment()">Save Payment</button></div></div>');};
window.savePayment=async function(){var sb=getClient(),lid=$('payloan').value,a=Number($('payamt').value||0);if(!lid||a<=0)return alert('Loan ID and Amount are required.');var l=db.loans.find(function(x){return String(x.loanId)===String(lid);});if(!l)return alert('Loan ID not found.');var r=await sb.from('loan_repayments').insert({loan_account_id:l.accountId,loan_id:Number(l.loanId),customer_id:l.customerId,amount:a,payment_amount:a,payment_date:$('paydate').value,payment_type:$('paytype').value,status:'successful',remarks:$('payremark').value||null,transaction_id:'PAY-'+Date.now()});if(r.error)return alert(err(r.error));var ur=await sb.from('loan_accounts').update({total_paid:l.paid+a,remaining_amount:Math.max(0,l.remaining-a)}).eq('id',l.accountId);if(ur.error)return alert(err(ur.error));closeM();await loadData();alert('Payment saved successfully.');};
function renderTransactions(){var p=$('transactions');if(!p)return;var html='<h2>Transactions</h2><div class="wrap"><table><tr><th>Transaction ID</th><th>Loan ID</th><th>Customer ID</th><th>Type</th><th>Amount</th><th>Method</th><th>Status</th><th>Date</th><th>Reference</th></tr>';db.transactions.forEach(function(x){html+='<tr><td>'+esc(x.transaction_id||x.id)+'</td><td>'+esc(x.loan_id)+'</td><td>'+esc(x.customer_id)+'</td><td>'+esc(x.transaction_type)+'</td><td>₹'+money(x.amount)+'</td><td>'+esc(x.payment_method)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.transaction_date||'')+'</td><td>'+esc(x.reference_number||'')+'</td></tr>';});html+='</table></div>';p.innerHTML=html;}
function renderStaff(){var p=$('staff');if(!p)return;var html='<h2>Staff/Admin</h2><button class="btn blue" onclick="addStaff()">+ Add Staff</button><div class="wrap"><table><tr><th>ID</th><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Created</th><th>Action</th></tr>';db.staff.forEach(function(x,i){html+='<tr><td>'+x.id+'</td><td>'+esc(x.name)+'</td><td>'+esc(x.email)+'</td><td>'+esc(x.role)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.created_at||'')+'</td><td><button class="btn gray" onclick="editStaff('+i+')">Edit</button></td></tr>';});html+='</table></div>';p.innerHTML=html;}
window.addStaff=function(){openBox('Add Staff/Admin','<div class="form">'+editField('Name','stn','')+editField('Email','ste','')+editField('Role','str','staff')+editField('Status','sts','active')+'<div class="full"><button class="btn green" onclick="saveStaff()">Save Staff</button></div></div>');};
window.saveStaff=async function(){var sb=getClient(),r=await sb.from('hfy_staff').insert({name:$('stn').value,email:$('ste').value||null,role:$('str').value||'staff',status:$('sts').value||'active'});if(r.error)return alert(err(r.error));closeM();await loadData();alert('Staff added successfully.');};
window.editStaff=function(i){var x=db.staff[i];openBox('Edit Staff','<div class="form">'+editField('Name','esn',x.name)+editField('Email','ese',x.email)+editField('Role','esr',x.role)+editField('Status','ess',x.status)+'<div class="full"><button class="btn blue" onclick="saveStaffEdit('+x.id+')">Save Changes</button></div></div>');};
window.saveStaffEdit=async function(id){var sb=getClient(),r=await sb.from('hfy_staff').update({name:$('esn').value,email:$('ese').value||null,role:$('esr').value,status:$('ess').value}).eq('id',id);if(r.error)return alert(err(r.error));closeM();await loadData();alert('Staff updated successfully.');};

function boot(){window.db=db;window.render=render;document.querySelectorAll('.m').forEach(function(el){el.onclick=function(){var txt=el.textContent||'';var id=txt.includes('Dashboard')?'dash':txt.includes('All Applications')?'apps':txt.includes('Approval')?'approval':txt.includes('Customer')?'customers':txt.includes('EMI / Repayment')?'repay':txt.includes('Payments')?'payments':txt.includes('Transactions')?'transactions':txt.includes('Overdue')?'overdue':txt.includes('Staff')?'staff':txt.includes('Reports')?'reports':null;if(id)show(id,el);else if(txt.includes('Home'))location.href='index.html';};});if($('search'))$('search').oninput=render;loadData();}
window.hfyMasterBoot=boot;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
