/* HELP FOR YOU — STAFF EMI VIEW + UPI PAY FLOW ONLY */
(function(){'use strict';
const M=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const E=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const D=v=>v?new Date(v).toLocaleDateString('en-IN'):'';
let groups=[];
function modal(h){let m=document.getElementById('staffPayModal');if(!m){m=document.createElement('div');m.id='staffPayModal';m.style='position:fixed;inset:0;background:#0008;display:none;align-items:center;justify-content:center;padding:18px;z-index:9999';m.innerHTML='<div style="background:#fff;border-radius:14px;padding:22px;width:min(900px,100%);max-height:92vh;overflow:auto"><div id="staffPayBody"></div></div>';document.body.appendChild(m)}document.getElementById('staffPayBody').innerHTML=h;m.style.display='flex'}
function close(){const m=document.getElementById('staffPayModal');if(m)m.style.display='none'}
function getEmis(){return Array.isArray(window.cache?.emis)?window.cache.emis:[]}
function render(){const t=document.getElementById('emiRows');if(!t)return;const a=getEmis();const map=new Map();a.forEach(x=>{const k=String(x.loan_account_id||x.loan_id||x.id);if(!map.has(k))map.set(k,[]);map.get(k).push(x)});groups=[...map.values()];groups.forEach(g=>g.sort((a,b)=>new Date(a.due_date)-new Date(b.due_date)));t.innerHTML=groups.map((g,i)=>{const f=g[0],c=(window.cache.customers||[]).find(x=>String(x.id)===String(f.customer_id));const name=f.customer_name||c?.full_name||'Customer',mobile=f.customer_mobile||c?.mobile||'',loan=f.loan_id||f.loan_account_id||'';const due=g.reduce((s,e)=>s+Math.max(0,Number(e.remaining_amount??(Number(e.total_due||Number(e.emi_amount||0)+Number(e.penalty||0))-Number(e.paid_amount||0)))),0),next=g.find(e=>Number(e.remaining_amount??0)>0)||f;return `<tr><td>${E(loan)}</td><td>${E(name)}</td><td>${E(mobile)}</td><td>${M(due)}</td><td>${D(next.due_date)}</td><td><button class="btn" onclick="staffViewLoanEmis(${i})">View</button></td></tr>`}).join('')||'<tr><td colspan="6">No EMI records</td></tr>'}
function view(i){const list=groups[i];if(!list?.length)return;const f=list[0],c=(window.cache.customers||[]).find(x=>String(x.id)===String(f.customer_id));const name=f.customer_name||c?.full_name||'Customer',mobile=f.customer_mobile||c?.mobile||'',loan=f.loan_id||f.loan_account_id||'';const rows=list.map(e=>{const total=Number(e.total_due||Number(e.emi_amount||0)+Number(e.penalty||0)),paid=Number(e.paid_amount||0),rem=Math.max(0,total-paid);return `<tr><td>${E(e.emi_number)}</td><td>${D(e.due_date)}</td><td>${M(e.emi_amount)}</td><td>${M(e.penalty)}</td><td>${M(total)}</td><td>${M(paid)}</td><td>${M(rem)}</td><td>${E(rem<=0?'paid':e.status)}</td><td>${rem>0?`<button class="btn green" onclick="staffOpenEmiPayment('${E(e.id)}')">Pay Now</button>`:'<span class="paid">Paid</span>'}</td></tr>`}).join('');modal(`<h2>All EMI — ${E(loan)}</h2><p><b>Name:</b> ${E(name)} &nbsp; <b>Mobile:</b> ${E(mobile)}</p><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;min-width:850px"><thead><tr><th>EMI No.</th><th>Due Date</th><th>EMI Amount</th><th>Penalty</th><th>Total Due</th><th>Paid</th><th>Remaining</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></div><div style="text-align:right;margin-top:14px"><button class="btn gray" onclick="staffClosePaymentModal()">Close</button></div>`)}
function pay(id){const e=getEmis().find(x=>String(x.id)===String(id));if(!e)return;const total=Number(e.total_due||Number(e.emi_amount||0)+Number(e.penalty||0)),rem=Math.max(0,total-Number(e.paid_amount||0));if(rem<=0){alert('This EMI is already paid.');return}const upi='upi://pay?pa=Q526188998@ybl&pn=HELP%20FOR%20YOU&am='+encodeURIComponent(rem.toFixed(2))+'&cu=INR&tn='+encodeURIComponent('EMI '+(e.emi_number||''));window.location.href=upi}
window.renderEmi=render;window.staffViewLoanEmis=view;window.staffOpenEmiPayment=pay;window.staffClosePaymentModal=close;window.staffRefreshEmi=render;
})();
