// HELP FOR YOU — Supabase client configuration
window.HFY_SUPABASE_URL = 'https://bvyruwvvlubgqficjblq.supabase.co';
window.HFY_SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2eXJ1d3Z2bHViZ3FmaWNqYmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0MzY1MDksImV4cCI6MjEwMjAxMjUwOX0.TRMtTPZrHHeShQKPkd8q1Qg_AEBW_Lo4zuWdgzMedbs';
